import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "module";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

if (fs.existsSync("build")) {
	fs.rmSync("build", { recursive: true, force: true });
}
fs.mkdirSync("build");

fs.copyFileSync("manifest.json", "build/manifest.json");
if (fs.existsSync("styles.css")) {
	fs.copyFileSync("styles.css", "build/styles.css");
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "build/main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	fs.watch("manifest.json", () => {
		try {
			fs.copyFileSync("manifest.json", "build/manifest.json");
			console.log("Updated manifest.json in build folder.");
		} catch (err) {
			console.error("Error updating manifest.json in build folder:", err);
		}
	});
	if (fs.existsSync("styles.css")) {
		fs.watch("styles.css", () => {
			try {
				fs.copyFileSync("styles.css", "build/styles.css");
				console.log("Updated styles.css in build folder.");
			} catch (err) {
				console.error("Error updating styles.css in build folder:", err);
			}
		});
	}
}
